### ISSUE TITLE
Function names should be consistent

### ISSUE THREAD

**Issue by mlist** [MPIIComputationalEpigenetics/DeepBlue-R#4]
Most functions so far follow the convenction deepblue.function_name. This should be consistent and needs to be applied to the helper methods, too.

**Comment by Nadia-Ashraf** [comment]
done!

**Comment by felipealbrecht** [comment]
The code does not work.

**Comment by Nadia-Ashraf** [comment]
Yes  because now I am updating the package so includes the functions with new names. As of now man/ has .Rd files with old function names.

**Comment by felipealbrecht** [comment]
So, dont say that the code is done when it is not and broke the build!!!

**Comment by Nadia-Ashraf** [comment]
I said done just for the naming convention. Sorry.

**Comment by felipealbrecht** [comment]
Okay, how long for fixingit?

**Comment by mlist** [comment]
function names are consistent
