### ISSUE TITLE
deepblue_flank with start < 0 and use_strand = T gives shifted regions on negative strand

### ISSUE THREAD

**Issue by quirinmanz** [MPIIComputationalEpigenetics/DeepBlue-R#47]
Hello,

I used the `deepblue_flank` command with the `use_strand`-flag and a negative value (e.g. -5000) to capture promoter regions of given genes. The resulting regions on the negative strand start 5kb upstream of the gene but then do not go towards the gene but rather even more upstream. (maybe the attached file can visualize this)
Did I understand the method the wrong way or is this a bug?

Best,
Quirin Manz

[visualization_flank.pdf](https://github.com/MPIIComputationalEpigenetics/DeepBlueR/files/3226433/visualization_flank.pdf)

**Comment by felipealbrecht** [comment]
Hello,
please, may you:
  past the used command
  the region with the problem
  the desired output

So, I can check the problem and answer you correctly (or fix a bug)

Thank you!

**Comment by ga89koc** [comment]
Hello,
thanks for the response.
This is my command:
```
> genes_query <- deepblue_select_genes(genes = c("ENSG00000187961.13","ENSG00000131591.17","ENSG00000215790.6","ENSG00000065526.10","ENSG00000280114.1"),
+                         gene_model = "gencode v23")
Called method: deepblue_select_genes
Reported status was: okay
> promoter_window <- deepblue_flank(genes_query, -5000, 5000, use_strand = T)
Called method: deepblue_flank
Reported status was: okay
> merged_query <- deepblue_merge_queries(promoter_window, genes_query)
Called method: deepblue_merge_queries
Reported status was: okay
> gene_regions_with_promotor <- deepblue_download_request_data(deepblue_get_regions(merged_query, "CHROMOSOME,START,END,STRAND"))
Called method: deepblue_get_regions
Reported status was: okay
> gene_regions_with_promotor
GRanges object with 10 ranges and 0 metadata columns:
       seqnames            ranges strand
          <Rle>         <IRanges>  <Rle>
   [1]     chr1     955587-960587      +
   [2]     chr1     960587-965715      +
   [3]     chr1   1081818-1116361      -
   [4]     chr1   1121361-1126361      -
   [5]     chr1   1724838-1745992      -
   [6]     chr1   1750992-1755992      -
   [7]     chr1 15842864-15847864      +
   [8]     chr1 15847864-15940460      +
   [9]     chr1 16681097-16688749      -
  [10]     chr1 16693749-16698749      -
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
```
So basically the `promotor_window` is shifted by 5kb.
The desired output would be:
```
> gene_regions_with_promotor
GRanges object with 10 ranges and 0 metadata columns:
       seqnames            ranges strand
          <Rle>         <IRanges>  <Rle>
   [1]     chr1     955587-960587      +
   [2]     chr1     960587-965715      +
   [3]     chr1   1081818-1116361      -
   [4]     chr1   1116361-1121361      -
   [5]     chr1   1724838-1745992      -
   [6]     chr1   1745992-1750992      -
   [7]     chr1 15842864-15847864      +
   [8]     chr1 15847864-15940460      +
   [9]     chr1 16681097-16688749      -
  [10]     chr1 16688749-16693749      -
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
```

Thanks!

**Comment by felipealbrecht** [comment]
I am verifying the code.
If I push a hotfix, can you test ASAP?
Also with other configurations (positive and negative strand, and positive
and negative start values)

**Comment by felipealbrecht** [comment]
FYI: Bug fixed -
https://github.com/MPIIComputationalEpigenetics/DeepBlue/commit/2100056016a4f4a4274a11d7fc986a56e1e352f3#diff-ce74e560e666fa2de0e5cbd7bf6827b5L81
New version online.

Please, remember to remove your previous request before re-executing your
workflow.

Thank you for the bug report!

**Comment by ga89koc** [comment]
As far as I can tell (I think I've tried all the possibilities), the method now does exactly what the description says. Thanks for the quick fix! 
Have a nice weekend!
