### ISSUE TITLE
Error when building vignettes: there is no package called 'Gviz'

### ISSUE THREAD

**Issue by felipealbrecht** [MPIIComputationalEpigenetics/DeepBlue-R#8]
Solution: Install dependencies in the devtools::install(...)

**Comment by felipealbrecht** [comment]
It is easily mitigated installing the Gviz manually.

**Comment by mlist** [comment]
It's not strictly a bug. The R installation process does not take care of installing bioconductor packages even though they are listed as required. The only way to solve this is to join bioconductor and have the package installation be controlled by the biocInstaller script.
